services:
  - type: web
    name: extractor-datos
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 10 --bind 0.0.0.0:$PORT --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
